# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root

# Clean old kitware repos, install system dependencies, ROS tools, and add zenoh repo
RUN apt-get update --allow-insecure-repositories \
    && apt-get install -y --no-install-recommends \
       ros-dev-tools ros-humble-rmw-cyclonedds-cpp \
       bridge-utils net-tools libaio-dev tmux tmuxinator \
    && apt-get update

# Install Python tools
RUN python3 -m pip install -U pysimplegui tk vcstool pymap3d

# Setup Aerostack2 workspace and build
RUN mkdir -p /root/aerostack2_ws/src/thirdparty \
    && cd /root/aerostack2_ws/src \
    && git clone -b mission_interpreter_improvements https://github.com/aerostack2/aerostack2.git \
    && cd /root/aerostack2_ws/src/aerostack2 \
    && git clone -b humble-devel https://github.com/MOCAP4ROS2-Project/mocap4r2_msgs.git thirdparty/mocap4r2_msgs \
    && git clone https://github.com/aerostack2/as2_platform_dji_psdk.git aerostack2/as2_aerial_platforms/as2_platform_dji_psdk \
    && touch /root/aerostack2_ws/src/aerostack2/as2_aerial_platforms/as2_platform_gazebo/COLCON_IGNORE \
    && touch /root/aerostack2_ws/src/aerostack2/as2_simulation_assets/COLCON_IGNORE \
    && touch /root/aerostack2_ws/src/aerostack2/as2_aerial_platforms/as2_platform_multirotor_simulator/COLCON_IGNORE \
    && cd /root/aerostack2_ws \
    && source /opt/ros/humble/setup.bash \
    && apt-get update \
    && rosdep update \
    && rosdep install -y -r -q --from-paths src --ignore-src \
    && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

# Setup PSDK workspace and build
RUN mkdir -p /root/psdk_ws/src \
    && cd /root/psdk_ws/src \
    && git clone -b 1.3.2 https://github.com/umdlife/psdk_ros2.git \
    && cd /root/psdk_ws \
    && source /opt/ros/humble/setup.bash \
    && rosdep install -y -r -q --from-paths src --ignore-src \
    && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

# Persist environment setup in .bashrc
RUN { \
      echo 'source /opt/ros/humble/setup.bash'; \
      echo 'export AEROSTACK2_PATH=$HOME/aerostack2_ws/src/aerostack2'; \
      echo 'source $AEROSTACK2_PATH/as2_cli/setup_env.bash'; \
      echo 'source /root/psdk_ws/install/setup.bash'; \
    } >> /root/.bashrc

WORKDIR /root/aerostack2_ws
